app:
  name: Dashboard_app
  reporterJobInterval: "@every 5m"
  sql:
    host:   localhost
    port:   3306
    user:   root
    pass:   root
    db:     stock_demo
  log:
    file: "dashboard_app.log"
    debug: true
  image:
    path: "/home/cemal/workstation/sirket/app/assets/ProductPhotos/"
